---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: terraform
outputs:
  - name: deployment
run:
  path: bosh-cpi-src-in/ci/pipelines/certify-stemcell/tasks/deploy-old-director.sh
params:
  BOSH_INIT_LOG_LEVEL:                    warn
  distro:                                 ""
  director_ca:                            ""
  director_ca_private_key:                ""
  bosh_openstack_ca_cert:                 replace-me
  v3_e2e_private_key_data:                ""
  old_bosh_release_version:               ""
  old_bosh_release_sha1:                  ""
  ci_bosh_admin_password:                 ""
  ci_v3_e2e_flavor:                       ""
  ci_v3_e2e_connection_timeout:           ""
  ci_v3_e2e_read_timeout:                 ""
  ci_v3_e2e_state_timeout:                ""
  ci_v3_e2e_write_timeout:                ""
  ci_v3_e2e_bosh_registry_port:           ""
  ci_v3_e2e_api_key:                      ""
  ci_v3_e2e_auth_url:                     ""
  ci_v3_e2e_project:                      ""
  ci_v3_e2e_domain:                       ""
  ci_v3_e2e_username:                     ""
  ci_time_server_1:                       ""
  ci_time_server_2:                       ""
  ci_old_openstack_cpi_release_version:   ""
  ci_old_openstack_cpi_release_sha1:      ""
  ci_old_bosh_stemcell_name:              ""
  ci_old_bosh_stemcell_version:           ""
  ci_old_bosh_stemcell_sha1:              ""
